steps:
# Debug: List files
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "=== Repository structure ==="
    ls -la
    echo "=== Contents of dummy_ingestion ==="
    ls -la ./dummy_ingestion/
    echo "=== End debug ==="

# Deploy the dummy data generator
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'generate-dummy-data'
  - '--gen2'
  - '--runtime=python311'
  - '--trigger-topic=dummy-data-topic'
  - '--entry-point=generate_dummy_data'
  - '--region=europe-west2'
  - '--source=./dummy_ingestion'