steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'insert-to-bigquery'
  - '--gen2'
  - '--runtime=python311'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--entry-point=insert_to_bigquery'
  - '--region=us-central1'
  - '--source=./ingestion'

timeout: '1600s'