steps:
# Deploy the main Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'insert-to-bigquery'
  - '--gen2'
  - '--runtime=python311'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--entry-point=insert_to_bigquery'
  - '--region=europe-west2'
  - '--source=./ingestion'

# Deploy the dummy data generator
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'generate-dummy-data'
  - '--gen2'
  - '--runtime=python311'
  - '--trigger-topic=dummy-data-topic'
  - '--entry-point=generate_dummy_data'
  - '--region=europe-west2'
  - '--source=./dummy_ingestion'

timeout: '1600s'